# MeshStatic Architecture Configuration

# Each tier node functions as both Data Center (DC) and Network Provider (NP)
# DC: Processing & Storage
# NP: High-Throughput Routing & Caching

tiers:
  tier1_edge:
    role_split: "DC:10%, NP:90%"
    description: "Ultra-low-latency caching and routing. Transient, session-level data only. Primary: Network Provider."
    cache:
      enabled: true
      type: memory
      eviction_policy: LRU
      max_size_mb: 128
    routing:
      latency_target_ms: 5
      failover:
        type: fast_reroute
        details: "Immediate reroute to next available edge node."
    metrics:
      endpoint: "/metrics/edge"
      report: "dc_np_ratio"

  tier2_core:
    role_split: "DC:50%, NP:50%"
    description: "Cross-tier service discovery and load balancing. Balanced DC/NP. Local data persistence."
    discovery:
      enabled: true
      protocol: "gRPC/HTTP"
    load_balancing:
      strategy: "round_robin"
    persistence:
      enabled: true
      type: "redis"
      local_db: true
    routing:
      throughput_target_mbps: 100
      failover:
        type: hybrid
        details: "Reroute for NP, data replication check for DC."
    metrics:
      endpoint: "/metrics/core"
      report: "dc_np_ratio"

  tier3_persistence:
    role_split: "DC:90%, NP:10%"
    description: "High-redundancy, asynchronous data replication and archival. Primary: Data Center."
    replication:
      enabled: true
      strategy: "async"
      redundancy: "3x"
    archival:
      enabled: true
      storage_type: "object_store"
    routing:
      minimal: true
      failover:
        type: data_replication_check
        details: "Verify data integrity and replicate to backup nodes."
    metrics:
      endpoint: "/metrics/persistence"
      report: "dc_np_ratio"

ideal_component:
  definition:
    - "Primary function percentage split (DC/NP)"
    - "Failover mechanism specific to split"
    - "Metric endpoint reporting DC/NP traffic ratio"
