artifact_location: file:///c:/Users/hp/Documents/Akulearn_docs/mlops/runs/mlflow/0
creation_time: 1765297513503
experiment_id: '0'
last_update_time: 1765297513503
lifecycle_stage: active
name: Default
