artifact_location: file:///c:/Users/hp/Documents/Akulearn_docs/mlops/runs/mlflow/350109360983722602
creation_time: 1765297514469
experiment_id: '350109360983722602'
last_update_time: 1765297514469
lifecycle_stage: active
name: exam-content-generation
