#!/usr/bin/env bash
# apply-migrations.sh — Automate Python/FastAPI migration across all Aku Platform services
#
# Usage (run from the Akulearn_docs repo root):
#   chmod +x docs/service-migrations/apply-migrations.sh
#
#   # Dry-run — preview every step without making changes
#   ./docs/service-migrations/apply-migrations.sh --all --dry-run
#
#   # Apply to all 9 services — clones each repo, runs bootstrap, opens PRs
#   ./docs/service-migrations/apply-migrations.sh --all
#
#   # Apply to a single service
#   ./docs/service-migrations/apply-migrations.sh AkuAI
#
# Prerequisites:
#   - gh CLI installed and authenticated (gh auth status)
#   - git installed
#   - bash 4+
#
# Migration tracker: docs/service-migrations/index.md

set -euo pipefail

# ── Constants ──────────────────────────────────────────────────────────────────

GITHUB_ORG="oumar-code"
BRANCH_NAME="feat/python-fastapi-migration"
COMMIT_MSG="feat: migrate to Python 3.11 / FastAPI"
PR_TITLE="feat: migrate to Python 3.11 / FastAPI"
PR_BODY="Automated migration scaffold generated by \`apply-migrations.sh\`.

## What's included
- Full Python 3.11 / FastAPI project structure (app/, tests/, alembic/)
- Dockerfile (multi-stage), docker-compose.yml
- GitHub Actions CI workflow
- pyproject.toml, requirements.txt, requirements-dev.txt
- .env.example, .gitignore, alembic.ini

## Next steps
1. Review generated files and add service-specific domain endpoints
2. See [migration tracker](https://github.com/${GITHUB_ORG}/Akulearn_docs/blob/main/docs/service-migrations/index.md) for domain endpoint specs
3. Merge this PR and update the tracker status to ✅ Done
"

# All 9 backend service repos in priority order
ALL_SERVICES=(
  AkuAI
  Akudemy
  Aku-EdgeHub
  Aku-IGHub
  Aku-Telhone
  Aku-SuperHub
  AkuTutor
  AkuWorkspace
  Aku-DaaS
)

# ── Resolve script location (works regardless of CWD) ─────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOTSTRAP_SCRIPT="${SCRIPT_DIR}/bootstrap.sh"
SCAFFOLDS_DIR="${SCRIPT_DIR}/scaffolds"

# ── Argument parsing ───────────────────────────────────────────────────────────

DRY_RUN=false
SERVICES=()

if [[ $# -eq 0 ]]; then
  echo "Error: no arguments provided." >&2
  echo "Usage: $0 --all [--dry-run]  |  $0 <ServiceName>" >&2
  exit 1
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --all)
      SERVICES=("${ALL_SERVICES[@]}")
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -*)
      echo "Error: unknown flag '$1'" >&2
      exit 1
      ;;
    *)
      SERVICES+=("$1")
      shift
      ;;
  esac
done

if [[ ${#SERVICES[@]} -eq 0 ]]; then
  echo "Error: no services specified." >&2
  exit 1
fi

# ── Helper: run or print a command ────────────────────────────────────────────

run() {
  if [[ "$DRY_RUN" == true ]]; then
    echo "  [dry-run] $*"
  else
    "$@"
  fi
}

# ── Pre-flight checks ──────────────────────────────────────────────────────────

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Aku Platform — Python/FastAPI Migration Automation"
if [[ "$DRY_RUN" == true ]]; then
  echo "  MODE: DRY RUN (no changes will be made)"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [[ ! -f "$BOOTSTRAP_SCRIPT" ]]; then
  echo "Error: bootstrap.sh not found at ${BOOTSTRAP_SCRIPT}" >&2
  exit 1
fi

if ! command -v gh &>/dev/null; then
  echo "Error: gh CLI is not installed. Install from https://cli.github.com" >&2
  exit 1
fi

if [[ "$DRY_RUN" == false ]]; then
  if ! gh auth status &>/dev/null; then
    echo "Error: gh CLI is not authenticated. Run: gh auth login" >&2
    exit 1
  fi
fi

if ! command -v git &>/dev/null; then
  echo "Error: git is not installed." >&2
  exit 1
fi

echo "Services to migrate: ${SERVICES[*]}"
echo ""

# ── Per-service migration function ────────────────────────────────────────────

SUCCEEDED=()
FAILED=()
SKIPPED=()

migrate_service() {
  local service="$1"
  local repo_url="https://github.com/${GITHUB_ORG}/${service}.git"
  local work_dir
  work_dir="$(mktemp -d)"

  echo "┌─ ${service} ─────────────────────────────────────────"
  echo "│  Repo:     ${GITHUB_ORG}/${service}"
  echo "│  Clone to: ${work_dir}"
  echo "│"

  # 1. Clone the target repo
  echo "│  Step 1: Clone ${repo_url}"
  if ! run git clone --depth 1 "${repo_url}" "${work_dir}"; then
    echo "│  ✗ Clone failed — skipping ${service}"
    echo "└──────────────────────────────────────────────────────"
    SKIPPED+=("${service}")
    return
  fi

  # 2. Run bootstrap.sh inside the cloned repo
  echo "│  Step 2: Run bootstrap.sh ${service}"
  run cp "${BOOTSTRAP_SCRIPT}" "${work_dir}/bootstrap.sh"
  if [[ "$DRY_RUN" == false ]]; then
    pushd "${work_dir}" > /dev/null
    bash bootstrap.sh "${service}"
    rm -f bootstrap.sh
    popd > /dev/null
  else
    echo "  [dry-run] pushd ${work_dir}"
    echo "  [dry-run] bash bootstrap.sh ${service}"
    echo "  [dry-run] rm -f bootstrap.sh"
    echo "  [dry-run] popd"
  fi

  # 3. Overlay service-specific scaffold files (if available)
  local scaffold_src="${SCAFFOLDS_DIR}/${service}"
  if [[ -d "$scaffold_src" ]]; then
    echo "│  Step 3: Overlay scaffold from ${scaffold_src}"
    run cp -r "${scaffold_src}/." "${work_dir}/"
  else
    echo "│  Step 3: No scaffold overlay found for ${service} (skipping overlay)"
  fi

  # 4. Create migration branch
  echo "│  Step 4: Create branch ${BRANCH_NAME}"
  if [[ "$DRY_RUN" == false ]]; then
    pushd "${work_dir}" > /dev/null
    git checkout -b "${BRANCH_NAME}"
    popd > /dev/null
  else
    echo "  [dry-run] pushd ${work_dir} && git checkout -b ${BRANCH_NAME} && popd"
  fi

  # 5. Stage and commit all generated files
  echo "│  Step 5: Commit scaffold"
  if [[ "$DRY_RUN" == false ]]; then
    pushd "${work_dir}" > /dev/null
    git add .
    git commit -m "${COMMIT_MSG}"
    popd > /dev/null
  else
    echo "  [dry-run] pushd ${work_dir} && git add . && git commit -m '${COMMIT_MSG}' && popd"
  fi

  # 6. Push the branch
  echo "│  Step 6: Push ${BRANCH_NAME}"
  if [[ "$DRY_RUN" == false ]]; then
    pushd "${work_dir}" > /dev/null
    git push origin "${BRANCH_NAME}"
    popd > /dev/null
  else
    echo "  [dry-run] pushd ${work_dir} && git push origin ${BRANCH_NAME} && popd"
  fi

  # 7. Open a pull request
  echo "│  Step 7: Open pull request"
  if [[ "$DRY_RUN" == false ]]; then
    pushd "${work_dir}" > /dev/null
    gh pr create \
      --repo "${GITHUB_ORG}/${service}" \
      --base main \
      --head "${BRANCH_NAME}" \
      --title "${PR_TITLE}" \
      --body "${PR_BODY}"
    popd > /dev/null
  else
    echo "  [dry-run] gh pr create --repo ${GITHUB_ORG}/${service} --base main --head ${BRANCH_NAME} --title '${PR_TITLE}'"
  fi

  # 8. Clean up temp directory
  if [[ "$DRY_RUN" == false ]]; then
    rm -rf "${work_dir}"
  fi

  echo "│  ✓ Done"
  echo "└──────────────────────────────────────────────────────"
  SUCCEEDED+=("${service}")
}

# ── Run migrations ─────────────────────────────────────────────────────────────

for svc in "${SERVICES[@]}"; do
  migrate_service "$svc" || FAILED+=("$svc")
  echo ""
done

# ── Summary ────────────────────────────────────────────────────────────────────

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Migration Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [[ ${#SUCCEEDED[@]} -gt 0 ]]; then
  echo "  ✅ Succeeded (${#SUCCEEDED[@]}): ${SUCCEEDED[*]}"
fi
if [[ ${#SKIPPED[@]} -gt 0 ]]; then
  echo "  ⚠️  Skipped   (${#SKIPPED[@]}): ${SKIPPED[*]}"
fi
if [[ ${#FAILED[@]} -gt 0 ]]; then
  echo "  ❌ Failed    (${#FAILED[@]}): ${FAILED[*]}"
fi

echo ""

if [[ "$DRY_RUN" == true ]]; then
  echo "  Dry-run complete. Re-run without --dry-run to apply changes."
else
  echo "  Next: update docs/service-migrations/index.md status to ✅ Done for each migrated service."
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [[ ${#FAILED[@]} -gt 0 ]]; then
  exit 1
fi
