#!/usr/bin/env bash
# sync-openapi-to-contracts.sh — Copy each service's generated openapi.yaml into
#                                the aku-platform-contracts repository under
#                                aku_contracts/openapi/<service>.yaml, then commit,
#                                push, and optionally re-tag the contracts repo.
#
# Usage (run from the directory that CONTAINS all service repos as immediate
#        subdirectories — same workspace layout as lint-format-tag.sh):
#
#   SERVICES_OVERRIDE="AkuAI Akudemy" TAG_OVERRIDE="v0.1.1" \
#     GHCR_USER="oumar-code" GH_PAT="<token>" \
#     ./sync-openapi-to-contracts.sh
#
# Environment variables:
#   SERVICES_OVERRIDE      — space-separated list of service repos (default: all 9)
#   TAG_OVERRIDE           — contracts repo tag to create / move  (default: v0.1.1)
#   GITHUB_ORG             — GitHub org (default: oumar-code)
#   GH_PAT                 — PAT with repo scope (required for push)
#
# What this script does:
#   1. Validates each service directory has an openapi.yaml (generated by
#      lint-format-tag.sh)
#   2. Clones oumar-code/aku-platform-contracts (or uses an existing clone at
#      ./aku-platform-contracts)
#   3. Ensures aku_contracts/openapi/ directory exists
#   4. Copies each service's openapi.yaml → aku_contracts/openapi/<service>.yaml
#   5. Commits and pushes (idempotent — skips empty commits)
#   6. Creates / updates the annotated tag on the contracts repo

set -euo pipefail

# ── Constants ──────────────────────────────────────────────────────────────────

SERVICES="${SERVICES_OVERRIDE:-AkuAI AkuTutor AkuWorkspace Akudemy Aku-EdgeHub Aku-IGHub Aku-Telhone Aku-SuperHub Aku-DaaS}"
TAG="${TAG_OVERRIDE:-v0.1.1}"
GITHUB_ORG="${GITHUB_ORG:-oumar-code}"
CONTRACTS_REPO="aku-platform-contracts"

# ── Helper: lowercase ─────────────────────────────────────────────────────────
to_lower() { echo "$1" | tr '[:upper:]' '[:lower:]'; }

# ── Step 1: Clone / update the contracts repo ─────────────────────────────────

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Syncing OpenAPI specs → ${GITHUB_ORG}/${CONTRACTS_REPO}"
echo "Tag: ${TAG}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

CONTRACTS_DIR="${CONTRACTS_REPO}"

if [[ -d "${CONTRACTS_DIR}/.git" ]]; then
  echo "Using existing clone at ./${CONTRACTS_DIR}"
  git -C "${CONTRACTS_DIR}" pull --ff-only
else
  if [[ -n "${GH_PAT:-}" ]]; then
    CONTRACTS_URL="https://x-access-token:${GH_PAT}@github.com/${GITHUB_ORG}/${CONTRACTS_REPO}.git"
  else
    CONTRACTS_URL="https://github.com/${GITHUB_ORG}/${CONTRACTS_REPO}.git"
  fi
  echo "Cloning ${GITHUB_ORG}/${CONTRACTS_REPO}..."
  git clone --depth 1 "${CONTRACTS_URL}" "${CONTRACTS_DIR}"
  git -C "${CONTRACTS_DIR}" config user.email "github-actions[bot]@users.noreply.github.com"
  git -C "${CONTRACTS_DIR}" config user.name  "github-actions[bot]"
  [[ -n "${GH_PAT:-}" ]] && git -C "${CONTRACTS_DIR}" remote set-url origin "${CONTRACTS_URL}"
fi

# Ensure target directory exists inside the contracts repo
OPENAPI_DIR="${CONTRACTS_DIR}/aku_contracts/openapi"
mkdir -p "${OPENAPI_DIR}"

# ── Step 2: Copy openapi.yaml from each service ───────────────────────────────

COPIED=0
MISSING=0

for svc in $SERVICES; do
  SRC="${svc}/openapi.yaml"
  DST="${OPENAPI_DIR}/$(to_lower "${svc}").yaml"

  if [[ -f "${SRC}" ]]; then
    cp "${SRC}" "${DST}"
    echo "  ✓ Copied ${svc}/openapi.yaml → aku_contracts/openapi/$(to_lower "${svc}").yaml"
    COPIED=$((COPIED + 1))
  else
    echo "  ⚠  ${svc}/openapi.yaml not found — run the lint/format/tag workflow first"
    MISSING=$((MISSING + 1))
  fi
done

echo ""
echo "Copied: ${COPIED}  |  Missing: ${MISSING}"
echo ""

# ── Step 3: Commit and push ───────────────────────────────────────────────────

pushd "${CONTRACTS_DIR}" > /dev/null

git add aku_contracts/openapi/

if git diff --cached --quiet; then
  echo "ℹ  No changes to openapi specs — nothing to commit"
else
  git commit -m "chore: sync openapi specs from all services (${TAG})"
  git push
  echo "✓ Committed and pushed updated OpenAPI specs"
fi

# ── Step 4: Tag the contracts repo ───────────────────────────────────────────

if git ls-remote --exit-code --tags origin "refs/tags/${TAG}" &>/dev/null; then
  echo "ℹ  Tag ${TAG} already exists on ${CONTRACTS_REPO} — skipping"
else
  git tag -a "${TAG}" -m "Release ${TAG} — includes OpenAPI specs for all 9 services"
  git push origin "${TAG}"
  echo "✓ Tagged ${CONTRACTS_REPO} at ${TAG}"
fi

popd > /dev/null

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OpenAPI sync complete."
echo "Specs are now at: ${GITHUB_ORG}/${CONTRACTS_REPO}/aku_contracts/openapi/"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
