apiVersion: apps/v1
kind: Deployment
metadata:
  name: aku-ig-hub
  labels:
    app: aku-ig-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aku-ig-hub
  template:
    metadata:
      labels:
        app: aku-ig-hub
    spec:
      containers:
        - name: ig-hub-api
          image: nginx:stable
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: aku-ig-hub-svc
spec:
  type: ClusterIP
  selector:
    app: aku-ig-hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
