artifact_uri: file:C:/Users/hp/Documents/Akulearn_docs/runs/mlflow/992841952367428707/772d05f13d444d4a9b100471df255f9c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '992841952367428707'
lifecycle_stage: active
run_id: 772d05f13d444d4a9b100471df255f9c
run_name: mlflow-integration-test
source_name: ''
source_type: 4
source_version: ''
start_time: 1764920575177
status: 1
tags: []
user_id: hp
