name: CI - IG Hub Example

on:
  push:
    paths:
      - 'infra/examples/ig_hub_control_panel/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'infra/examples/ig_hub_control_panel/**'
      - 'tests/**'

jobs:
  test-ig-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastapi uvicorn

      - name: Run tests
        run: |
          pytest -q
